title: Alex Makes
logo: /assets/img/logo.png
description: As a Material Scientist, I am passionate about using my skills to develop innovative materials and technologies that improve the built environment and protect against cyber threats. With experience in developing synthetic Nacre.
show_downloads: false
theme: jekyll-theme-minimal
